# Generated by Django 4.1.7 on 2023-03-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_amountingredientinrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
