# Generated by Django 4.1.7 on 2023-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_favorite_unique_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amountingredientinrecipe',
            name='unique_recipe_ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_for_author',
        ),
        migrations.AddConstraint(
            model_name='amountingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient', violation_error_message='У вас уже есть этот инредиент в рецепте'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_for_author', violation_error_message='У вас уже есть рецепт с таким названием'),
        ),
    ]
